In [2]:
import numpy as np
import pcl
from pcl import IterativeClosestPoint

In [4]:
def computeICPDelta(source, target, iters=10) :
    global currMap

    source_array = source.to_array()
    target_array = target.to_array()
    
    # Take all points in a radius of +/- 20 mts and height < 0.1 mt ..
    source_min_array = source_array[np.where((abs(source_array[:,0]) < 20) & 
                                    (abs(source_array[:,1]) < 20) & (source_array[:,2] >= 0.1))]
    target_min_array = target_array[np.where((abs(target_array[:,0]) < 20) & 
                                            (abs(target_array[:,1]) < 20) & (target_array[:,2] >= 0.1))]

    source_min_cloud = pcl.PointCloud(source_min_array)
    target_min_cloud = pcl.PointCloud(target_min_array)

    icp = source_min_cloud.make_IterativeClosestPoint()
    #icp.setTransformationEpsilon(0.05)
    if ((source_min_cloud.size > 0) & (target_min_cloud.size > 0)) :
        converged, transf, estimate, fitness = icp.icp(source_min_cloud, target_min_cloud, max_iter=iters)
        print(converged, estimate, fitness)
        print(icp)
        if (converged) :
            if (fitness < 0.2) :
                print("Fitness quality ok")
            print(transf)
        else :
            print("ICP fails to converge")
    else :
        print("No points for ICP")
        transf = None

    return transf

In [5]:
p1 = pcl.load('/home/prasad/nloptimize/2000.pcd')
p2 = pcl.load('/home/prasad/nloptimize/2003.pcd')

In [6]:
computeICPDelta(p1, p2)

True <PointCloud of 3881 points> 0.1363196845495376
Fitness quality ok
[[  9.99987543e-01   5.19099180e-03  -2.32566708e-05   1.54614784e-02]
 [ -5.19119529e-03   9.99980688e-01   3.77186877e-03  -8.90814900e-01]
 [  4.28364801e-05  -3.77168832e-03   9.99994040e-01   2.39746203e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00]]


/home/prasad/.local/lib/python3.5/site-packages/ipykernel_launcher.py:19: DeprecationWarning: Non length-one string passed in for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead


array([[  9.99987543e-01,   5.19099180e-03,  -2.32566708e-05,
          1.54614784e-02],
       [ -5.19119529e-03,   9.99980688e-01,   3.77186877e-03,
         -8.90814900e-01],
       [  4.28364801e-05,  -3.77168832e-03,   9.99994040e-01,
          2.39746203e-03],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00]], dtype=float32)