In [71]:
import numpy as np
import math

In [72]:
src =  np.array([[0.0, 0.0, 1.0], [0.0, 1.0, 1.0], [1.0, 0.0,1.0], [1.0, 1.0, 1.0]])
src = src.T
print(src)

[[ 0.  0.  1.  1.]
 [ 0.  1.  0.  1.]
 [ 1.  1.  1.  1.]]


In [73]:
# Create a transformation matrix for 45 deg rotation and translation of (2,5, 1.5)
tm = np.array([[0.707, -0.707, 2.5], [0.707, 0.707, 1.0], [0, 0, 1]])
print("TM : ")
print(tm)
tgt = np.dot(tm, src)
print("SRC : ")
print(src)
print("TGT : ")
print(tgt)

TM : 
[[ 0.707 -0.707  2.5  ]
 [ 0.707  0.707  1.   ]
 [ 0.     0.     1.   ]]
SRC : 
[[ 0.  0.  1.  1.]
 [ 0.  1.  0.  1.]
 [ 1.  1.  1.  1.]]
TGT : 
[[ 2.5    1.793  3.207  2.5  ]
 [ 1.     1.707  1.707  2.414]
 [ 1.     1.     1.     1.   ]]


In [74]:
# Get the non-honogenous forms for the src and tgt and
# compute the H4 matrix
src_nh = src[0:2,]
tgt_nh = tgt[0:2,]
print("SRC NH : ")
print(src_nh)
print("TGT_NH : ")
print(tgt_nh)
#h4 = computeH4In2D(src_nh, tgt_nh)
h4 = tgt_nh - src_nh
print("H4 : ")
print(h4)

SRC NH : 
[[ 0.  0.  1.  1.]
 [ 0.  1.  0.  1.]]
TGT_NH : 
[[ 2.5    1.793  3.207  2.5  ]
 [ 1.     1.707  1.707  2.414]]
H4 : 
[[ 2.5    1.793  2.207  1.5  ]
 [ 1.     0.707  1.707  1.414]]


In [75]:
def computeHomographyFromH4P(H4p, img_dims):
    print(H4p.shape)
    ps = np.array([[0,0],[0,img_dims[1]], [img_dims[0],0],[img_dims[0],img_dims[1]]])
    
    print(ps.shape)
    print("PS : ",ps)
    qs = ps + H4p
    print("QS : ", qs)

    P = np.zeros((9,9))
    for i in range(4):

        P[2*i]   = np.array([-ps[i,0], -ps[i,1], -1, 0, 0, 0, ps[i,0]*qs[i,0], ps[i,1]*qs[i,0], qs[i,0]])
        P[2*i+1] = np.array([0, 0, 0, -ps[i,0], -ps[i,1], -1, ps[i,0]*qs[i,1], ps[i,1]*qs[i,1], qs[i,1]])

    P[-1,-1] = 1

    b = np.zeros((9))
    b[-1] = 1

    H = np.linalg.solve(P,b)

    return H

In [76]:
#tm = np.array([[0.707, -0.707, 2.5], [0.707, 0.707, 1.0], [0, 0, 1]])
#print(tm)
#src =  np.array([[1.0, 1.0, 1.0], [1.0, 2.0, 1.0], [2.0, 1.0,1.0], [2.0, 2.0, 1.0]])
#src = src - np.array([1,1,0])

In [77]:
h4 = h4.T
h = computeHomographyFromH4P(h4, [1,1])
print(h, h.shape)

(4, 2)
(4, 2)
PS :  [[0 0]
 [0 1]
 [1 0]
 [1 1]]
QS :  [[ 2.5    1.   ]
 [ 1.793  1.707]
 [ 3.207  1.707]
 [ 2.5    2.414]]
[ 0.707 -0.707  2.5    0.707  0.707  1.    -0.     0.     1.   ] (9,)


In [79]:
h = h.reshape((3,3))
print(h)
print(tm)

[[ 0.707 -0.707  2.5  ]
 [ 0.707  0.707  1.   ]
 [-0.     0.     1.   ]]
[[ 0.707 -0.707  2.5  ]
 [ 0.707  0.707  1.   ]
 [ 0.     0.     1.   ]]


In [84]:
srclarge =  np.array([[0.0, 0.0, 1.0], [0.0, 64.0, 1.0], [64.0, 0.0,1.0], [64.0, 64.0, 1.0]])
tgt = np.dot(tm, srclarge.T)
print("SRC : ")
print(srclarge)
print("TGT : ")
print(tgt)

SRC : 
[[  0.   0.   1.]
 [  0.  64.   1.]
 [ 64.   0.   1.]
 [ 64.  64.   1.]]
TGT : 
[[  2.5   -42.748  47.748   2.5  ]
 [  1.     46.248  46.248  91.496]
 [  1.      1.      1.      1.   ]]


In [87]:
src_nh = srclarge.T[0:2,]
tgt_nh = tgt[0:2,]
print("SRC NH : ")
print(src_nh)
print("TGT_NH : ")
print(tgt_nh)
#h4 = computeH4In2D(src_nh, tgt_nh)
h4 = tgt_nh - src_nh
print("H4 : ")
print(h4)

SRC NH : 
[[  0.   0.  64.  64.]
 [  0.  64.   0.  64.]]
TGT_NH : 
[[  2.5   -42.748  47.748   2.5  ]
 [  1.     46.248  46.248  91.496]]
H4 : 
[[  2.5   -42.748 -16.252 -61.5  ]
 [  1.    -17.752  46.248  27.496]]


In [90]:
h4 = h4.T
h = computeHomographyFromH4P(h4, [64,64])
print(h, h.shape)

(2, 4)
(4, 2)
PS :  [[ 0  0]
 [ 0 64]
 [64  0]
 [64 64]]


ValueError: operands could not be broadcast together with shapes (4,2) (2,4) 

In [91]:
h = h.reshape((3,3))
print(h)
print(tm)

[[-17.752 -45.248   2.5  ]
 [ 45.248 -17.752   1.   ]
 [ -0.      0.      1.   ]]
[[ 0.707 -0.707  2.5  ]
 [ 0.707  0.707  1.   ]
 [ 0.     0.     1.   ]]
